const productsJsonData = {
        "products": [
          {
            "asin": "B0CSB1GX4H",
            "product_title": "Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Yellow)",
            "product_price": "$169.99",
            "product_original_price": null,
            "currency": "USD",
            "product_star_rating": "4.5",
            "product_num_ratings": 77,
            "product_url": "https://www.amazon.com/dp/B0CSB1GX4H",
            "product_photo": "https://m.media-amazon.com/images/I/51rK-Be8dxL._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$169.99",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": false,
            "climate_pledge_friendly": false,
            "sales_volume": "500+ bought in past month",
            "delivery": "FREE delivery Wed, Apr 17 Only 1 left in stock - order soon."
          },
          {
            "asin": "B0BQ118F2T",
            "product_title": "Moto G Play 2023 3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue",
            "product_price": "$99.99",
            "product_original_price": "$169.99",
            "currency": "USD",
            "product_star_rating": "4.1",
            "product_num_ratings": 2291,
            "product_url": "https://www.amazon.com/dp/B0BQ118F2T",
            "product_photo": "https://m.media-amazon.com/images/I/61K1Fz5LxvL._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$99.99",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": true,
            "climate_pledge_friendly": false,
            "sales_volume": "2K+ bought in past month",
            "delivery": "FREE delivery Sat, Apr 20 Or fastest delivery Wed, Apr 17"
          },
          {
            "asin": "B0CN1Q2X3B",
            "product_title": "SAMSUNG Galaxy A25 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Advanced Triple Camera System, Expandable Storage, Stereo Speakers,US Version,2024,Black",
            "product_price": "$300.00",
            "product_original_price": null,
            "currency": "USD",
            "product_star_rating": "4.3",
            "product_num_ratings": 1995,
            "product_url": "https://www.amazon.com/dp/B0CN1Q2X3B",
            "product_photo": "https://m.media-amazon.com/images/I/61cwMOVn17L._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$300.00",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": true,
            "climate_pledge_friendly": false,
            "sales_volume": "1K+ bought in past month",
            "delivery": "FREE delivery Sat, Apr 20 Or fastest delivery Today 5 PM - 10 PM"
          },
          {
            "asin": "B0CSDZP44V",
            "product_title": "BLU G73 | 2023 | 3-Day Battery | Unlocked | 6.8” HD+ Infinity Display | 128/6GB | Triple 50MP Camera | US Version | US Warranty | Grey",
            "product_price": "$99.99",
            "product_original_price": "$149.99",
            "currency": "USD",
            "product_star_rating": "4.4",
            "product_num_ratings": 18,
            "product_url": "https://www.amazon.com/dp/B0CSDZP44V",
            "product_photo": "https://m.media-amazon.com/images/I/81TeO+nqxnL._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$99.99",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": true,
            "climate_pledge_friendly": false,
            "sales_volume": "400+ bought in past month",
            "delivery": "FREE delivery Sat, Apr 20 Or fastest delivery Tomorrow, Apr 16"
          },
          {
            "asin": "B092NTYZ78",
            "product_title": "Panasonic Compact Cordless Phone with DECT 6.0, 1.6&quot; Amber LCD and Illuminated HS Keypad, Call Block, Caller ID, Multiple Display Languages - 1 Handset - KX-TGB810S (Black/Silver)",
            "product_price": "$24.99",
            "product_original_price": null,
            "currency": "USD",
            "product_star_rating": "4.2",
            "product_num_ratings": 4849,
            "product_url": "https://www.amazon.com/dp/B092NTYZ78",
            "product_photo": "https://m.media-amazon.com/images/I/81k6vcykYYL._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$24.99",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": true,
            "climate_pledge_friendly": false,
            "sales_volume": "2K+ bought in past month",
            "delivery": "FREE delivery Sat, Apr 20 on $35 of items shipped by AmazonOr fastest delivery Today 5 PM - 10 PM"
          },
          {
            "asin": "B09T3MQSVP",
            "product_title": "Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM Unlocked Android Smartphone, 64GB, Long Lasting Battery, Expandable Storage, Triple Lens Camera, Infinite Display, Black (Renewed)",
            "product_price": "$98.99",
            "product_original_price": "$119.99",
            "currency": "USD",
            "product_star_rating": "3.8",
            "product_num_ratings": 1001,
            "product_url": "https://www.amazon.com/dp/B09T3MQSVP",
            "product_photo": "https://m.media-amazon.com/images/I/61xhaqnlKPL._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$98.99",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": false,
            "climate_pledge_friendly": true,
            "sales_volume": "1K+ bought in past month",
            "delivery": "FREE delivery Tomorrow, Apr 16"
          },
          {
            "asin": "B0CRDXJK6T",
            "product_title": "Unlocked Android Phones A24 Ultra Cell Phone 2024 Android 13 Mobile Phone with Build-in Pen, 12GB+512GB, 6.8&quot; Display, 50MP+24MP Camera 6500 mAh 4G Dual SIM (Black)",
            "product_price": "$189.99",
            "product_original_price": "$199.99",
            "currency": "USD",
            "product_star_rating": "4.6",
            "product_num_ratings": 4,
            "product_url": "https://www.amazon.com/dp/B0CRDXJK6T",
            "product_photo": "https://m.media-amazon.com/images/I/61hWh7R7xwL._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$189.99",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": true,
            "climate_pledge_friendly": false,
            "sales_volume": "50+ bought in past month",
            "delivery": "FREE delivery Sat, Apr 20 Or fastest delivery Tomorrow, Apr 16"
          },
          {
            "asin": "B0BLZN9NDG",
            "product_title": "SAMSUNG,Galaxy A04e (SM-A042M/DS) Dual SIM 32GB,6.5&#x27;&#x27; GSM Unlocked,International Version-Black",
            "product_price": "$95.65",
            "product_original_price": "$105.00",
            "currency": "USD",
            "product_star_rating": "3.9",
            "product_num_ratings": 206,
            "product_url": "https://www.amazon.com/dp/B0BLZN9NDG",
            "product_photo": "https://m.media-amazon.com/images/I/71O2YkTlq-L._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$95.65",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": true,
            "climate_pledge_friendly": false,
            "sales_volume": "1K+ bought in past month",
            "delivery": "FREE delivery Sat, Apr 20 Or fastest delivery Tomorrow, Apr 16"
          },
          {
            "asin": "B0CKNHHZH1",
            "product_title": "Reno10 Cheap Smartphone， 5.0&#x27;&#x27; Android 9.0, 16GB ROM(Extendable to 128GB,Dual SIM Dual Camera, WiFi,Bluetooth,GPS Basic Mobile Phones (Reno10-Purple)",
            "product_price": "$54.99",
            "product_original_price": null,
            "currency": "USD",
            "product_star_rating": "2.9",
            "product_num_ratings": 24,
            "product_url": "https://www.amazon.com/dp/B0CKNHHZH1",
            "product_photo": "https://m.media-amazon.com/images/I/51p6UE+Jm9L._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$54.99",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": true,
            "climate_pledge_friendly": false,
            "sales_volume": "50+ bought in past month",
            "delivery": "FREE delivery Sat, Apr 20 Or fastest delivery Tomorrow, Apr 16"
          },
          {
            "asin": "B0CHH6X6H2",
            "product_title": "Samsung Galaxy A03s, 32GB, Black - Prepaid Smartphone (Locked)",
            "product_price": "$49.99",
            "product_original_price": null,
            "currency": "USD",
            "product_star_rating": "4.1",
            "product_num_ratings": 80,
            "product_url": "https://www.amazon.com/dp/B0CHH6X6H2",
            "product_photo": "https://m.media-amazon.com/images/I/812woqv69CL._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$49.99",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": true,
            "climate_pledge_friendly": false,
            "sales_volume": "1K+ bought in past month",
            "delivery": "FREE delivery Sat, Apr 20 Or fastest delivery Today 5 PM - 10 PM"
          },
          {
            "asin": "B0CP4FMLBT",
            "product_title": "BLU C5L MAX | 2024 | All-Day Battery | GSM Unlocked | 5.7” Display | 16/2GB |US Version | US Warranty | Black",
            "product_price": "$49.90",
            "product_original_price": null,
            "currency": "USD",
            "product_star_rating": "3.4",
            "product_num_ratings": 112,
            "product_url": "https://www.amazon.com/dp/B0CP4FMLBT",
            "product_photo": "https://m.media-amazon.com/images/I/81No0c60jdL._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$49.90",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": true,
            "climate_pledge_friendly": false,
            "sales_volume": "1K+ bought in past month",
            "delivery": "FREE delivery Sat, Apr 20 Or fastest delivery Wed, Apr 17 Only 1 left in stock - order soon."
          },
          {
            "asin": "B00N22M0XS",
            "product_title": "AT&amp;T EL51203 - 2 Handset Cordless Phone Full-Duplex Handset Speakerphone, Caller ID/Call Waiting",
            "product_price": "$30.72",
            "product_original_price": "$43.95",
            "currency": "USD",
            "product_star_rating": "4.3",
            "product_num_ratings": 16904,
            "product_url": "https://www.amazon.com/dp/B00N22M0XS",
            "product_photo": "https://m.media-amazon.com/images/I/71yY8CDrnxL._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$30.72",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": true,
            "climate_pledge_friendly": false,
            "sales_volume": "2K+ bought in past month",
            "delivery": "FREE delivery Sat, Apr 20 on $35 of items shipped by AmazonOr fastest delivery Tomorrow, Apr 16"
          },
          {
            "asin": "B08PMYLKVF",
            "product_title": "Apple iPhone 12 Pro, 128GB, Pacific Blue - Fully Unlocked (Renewed)",
            "product_price": "$370.88",
            "product_original_price": "$521.01",
            "currency": "USD",
            "product_star_rating": "4.2",
            "product_num_ratings": 8239,
            "product_url": "https://www.amazon.com/dp/B08PMYLKVF",
            "product_photo": "https://m.media-amazon.com/images/I/51n-83C8HYL._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$370.88",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": true,
            "climate_pledge_friendly": true,
            "sales_volume": "2K+ bought in past month",
            "delivery": "FREE delivery Tomorrow, Apr 16"
          },
          {
            "asin": "B07ZPJW2XH",
            "product_title": "Apple iPhone 11, 64GB, White - Fully Unlocked (Renewed)",
            "product_price": "$223.00",
            "product_original_price": "$244.95",
            "currency": "USD",
            "product_star_rating": "4.3",
            "product_num_ratings": 48916,
            "product_url": "https://www.amazon.com/dp/B07ZPJW2XH",
            "product_photo": "https://m.media-amazon.com/images/I/31PY10NqSLL._AC_SX444_SY639_FMwebp_QL65_.jpg",
            "product_num_offers": null,
            "product_minimum_offer_price": "$223.00",
            "is_best_seller": false,
            "is_amazon_choice": false,
            "is_prime": false,
            "climate_pledge_friendly": true,
            "sales_volume": "500+ bought in past month",
            "delivery": "FREE delivery Apr 18 - 19 Or fastest delivery Tomorrow, Apr 16 Only 1 left in stock - order soon."
          }
        ]
    }



    export { productsJsonData  };